"""
Django settings for bookstore_project project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads variables from a .env file (in the project root, next to manage.py)
# into the environment — that's where RAZORPAY_KEY_ID / RAZORPAY_KEY_SECRET
# below actually come from. .env is git-ignored on purpose: it holds your
# real keys, so it should never be committed or shared.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-tp+8lm&u4*$$bl3&asd&ebta6idur9q^^tt^b50wq1$4z4b9i3',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get(
    'ALLOWED_HOSTS', 'localhost,127.0.0.1'
).split(',')

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# ---- Razorpay ----
# Get these from https://dashboard.razorpay.com/app/keys (Test Mode keys to
# start with — they look like rzp_test_xxxxxxxx / a 24-char secret).
# NEVER hardcode real keys here — set them as environment variables instead
# (see the README section this change adds for how, on your OS / host).
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', '')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Inkwell Books apps
    'core',
    'catalog',
    'cart',
    'accounts',
    'orders',
    'chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bookstore_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookstore_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ---- Neon (Postgres) ----
# If a DATABASE_URL is set (in your .env locally, or as an environment
# variable on Render/wherever you deploy), it overrides the SQLite default
# above and points Django at your Neon database instead. Get this URL from
# your Neon project's "Connect" button — it looks like:
#   postgresql://<user>:<password>@<host>/<dbname>?sslmode=require
# Leaving it unset (e.g. on your own laptop) keeps using SQLite as before.
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    import dj_database_url
    DATABASES['default'] = dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# User-uploaded files (profile avatars, etc.)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'



# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# By default we use the console backend, which just prints emails to the
# terminal instead of actually sending them -- handy for local development
# so you can see the welcome email without setting up SMTP.
#
# To send REAL emails for free using Gmail SMTP:
#   1. Turn on 2-Step Verification on the Gmail account: https://myaccount.google.com/security
#   2. Create an "App Password": https://myaccount.google.com/apppasswords
#   3. Set the two environment variables below before running the server:
#        set EMAIL_HOST_USER=youraddress@gmail.com        (Windows)
#        set EMAIL_HOST_PASSWORD=your16charapppassword
#      or on Mac/Linux:
#        export EMAIL_HOST_USER=youraddress@gmail.com
#        export EMAIL_HOST_PASSWORD=your16charapppassword
#   Gmail's free tier allows roughly 500 emails/day.

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'bookstore.inkwell@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
else:
    # No SMTP credentials set -> just print emails to the console/log instead
    # of failing. Set EMAIL_HOST_USER / EMAIL_HOST_PASSWORD to send for real.
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = f'Inkwell Books <{EMAIL_HOST_USER or "noreply@inkwellbooks.com"}>'
